name: Build and Deploy  # 更新名称以明确包含部署功能

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write  # 新增：允许操作 GitHub Pages
  id-token: write  # 新增：用于身份验证

jobs:
  check:
    strategy:
      matrix:
        node: [ 22, 23 ]
    runs-on: ubuntu-latest
    name: Astro Check for Node.js ${{ matrix.node }}
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Astro Check
        run: pnpm astro check

  build:
    needs: check  # 依赖检查通过后再执行构建
    strategy:
      matrix:
        node: [ 22 ]  # 部署阶段只需一个 Node 版本即可
    runs-on: ubuntu-latest
    name: Build and Deploy to GitHub Pages
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Astro Build
        run: pnpm astro build  # 生成 dist 目录

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3  # 上传 dist 作为部署产物
        with:
          path: './dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # 部署到 GitHub Pages
        with:
          artifact_name: github-pages  # 与上传的产物名称匹配

      - name: Show deployment URL
        run: echo "Site deployed to https://${{ github.repository_owner }}.github.io/"